version: '2'
services:
  app:
    container_name: poc
    restart: always
    build: .
    ports:
      - '8080:8080'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mvertes/alpine-mongo:4.0.5-0
    volumes:
      - ./data/mongo:/data/db
    ports:
      - '27017:27017'
